version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_started
    volumes:
      - .:/app
      - /app/node_modules
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - carnet

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - carnet

networks:
  carnet:
    driver: bridge
